---
# This role builds the network and wireless configuration for the extender router

- name: Create Dropbear folder
  file:
    path: "{{source_dir}}/files/etc/dropbear/"
    state: directory
    mode: 0700

- name: Add keys to login
  lineinfile:
    dest: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    line: "{{item}}"
    state: present
    create: true
  with_items: "{{keys_to_insert}}"
  when: insert_keys

- name: Authorized keys only readable by owner
  file:
    path: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    mode: 0600
  when: insert_keys

- name: Create the UCI config folder
  file:
    path: "{{source_dir}}/files/etc/config/"
    state: directory

- name: Template dropbear config
  template:
    src: "dropbear.j2"
    dest: "{{source_dir}}/files/etc/config/dropbear"

- name: Template firewall config
  template:
    src: "firewall.j2"
    dest: "{{source_dir}}/files/etc/config/firewall"

# Network and wifi stuff is hardware specific, so we keep templates for each
# supported device. it really shouldn't ever change much in upstream LEDE
# but do remember it's possible
- name: Template network interface configuration
  template:
    src: "{{final_device_template}}-network.j2"
    dest: "{{source_dir}}/files/etc/config/network"

- name: Insert Lan network
  blockinfile:
    insertbefore: BOF
    marker: "#LAN"
    path: "{{source_dir}}/files/etc/config/network"
    block: |
      config interface 'lan'
          option type 'bridge'
          option ifname '{{lan_interfaces}}'
          option proto 'dhcp'


# we insert boilerplate stuff into the network configs here for the sake of de-duplication
- name: Insert Loopback network
  blockinfile:
    insertbefore: BOF
    marker: "#LO"
    path: "{{source_dir}}/files/etc/config/network"
    block: |
      config interface 'loopback'
          option ifname 'lo'
          option proto 'static'
          option ipaddr '127.0.0.1'
          option netmask '255.0.0.0'

- name: Template wifi interface configuration
  template:
    src: "{{final_device_template}}-wireless.j2"
    dest: "{{source_dir}}/files/etc/config/wireless"
  when: wireless_conf_path is file

- name: Template package update url
  template:
    src: customfeeds.conf.j2
    dest: "{{source_dir}}/files/etc/opkg/customfeeds.conf"
