rita_type: "client"
logging_enabled: false
logging_level: "WARN"
logging_url: "https://stats.altheamesh.com:9999/compressed_sink/"
source_dir: build
disable_password_login: false
remote_mesh_access: false
insert_keys: false
keys_to_insert:
  - ""
dropbear_wan_accessible: false
ssh_port: 22
password_auth: 0
default_price: 100
final_device_template: "{{ conf_to_build if device_template is not defined else device_template }}"
wireless_conf_path: "{{role_path}}/templates/{{final_device_template}}-wireless.j2"

mesh_subnets:
  - "f000::/4" # locally routable address and link local addresses, link local isn't forwarded anyways
  - "2000::/4" # most assigned unicast addresses
  - "3000::/4" # some depricated stuff
  - "4000::/4" # some depricated stuff
  - "5000::/4" # some depricated stuff

wifi_key: "ChangeMe"

lan_ip: "192.168.10.1"

# should default to sae-mixed (WPA3/2), which depends on wpad-basic-wolfssl and is enabled by default in openwrt-21.02
# due to high rate of incompatible devices default remains wpa2 only, this should be changed back in the future
wifi_encryption: "psk2+tkip+ccmp"

hardcoded_interfaces:
  - "mesh"

listen_interfaces_extended: "{{listen_interfaces + hardcoded_interfaces}}"

####### exit defaults

allowed_country_codes: "['US']"
# database_uri: "postgresql://..."
description: "Althea Exit Description"
remote_log: "false"
workers: 1

### [exit_network]
entry_timeout: 7776000
exit_hello_port: 4875
exit_price: 10000000
exit_start_ip: "172.168.0.100"
# geoip_api_key: ""
# geoip_api_user: ""
own_internal_ip: "172.168.0.254"
own_internal_netmask: 16
wg_tunnel_port: 60000

### [localization]
display_currency_symbol: "true"
wyre_enabled: "false"

### [localization.support_number.code]
support_number_code_source: "plus"
support_number_code_value: 1

### [localization.support_number.national]
support_number_value: 8664258432
support_number_zeroes: 0

### [network]
bounty_port: 8888
exit_mesh_ip: "fd01::1/128"
exit_metric_factor: 1900
exit_direct_peer_interfaces: []
exit_direct_peer_vlans: []
nickname: "Althea Exit"
rita_dashboard_port: 4877
rita_hello_port: 4876
# wan_interface: "eth0"
# wan_proto: "dhcp"
# wan_ipaddr: "1.1.1.2/24"
# wan_ip6addr: "fd00::1/8"
# wan_gateway: "1.1.1.1"
# wan_dns:
#   - "8.8.8.8"
#   - "8.8.4.4"
wg_private_key: ""
wg_public_key: ""
wg_start_port: 60000

### [network.shaper_settings]
network_shaper_enabled: "true"

### [payment]
bridge_enabled: "true"
debt_limit_enabled: "true"
eth_private_key: "0x0101010101010101010101010101010101010101"
free_tier_throughput: 1000
max_fee: 20000000
full_nodes: ["https://dai.althea.net:443"]
system_chain: "Xdai"

### [verif_settings]
mailer: false
# email_address: "exit@example.com"
# smtp_url: "smtp.fastmail.com"
# smtp_domain: "mail.example.com"
# smtp_username: "exit@example.com"
# smtp_password: ""
# balance_notification_interval: 86400
# notify_low_balance: "true"
# test: "false"
# test_dir: ""
phone: false
# phone_auth_api_key: ""
# send_number: "+15555555555"
# twillio_account_id: ""
# twillio_auth_token: ""
# balance_notification_body: "Your Althea router has a low balance! Your service will be slow until more funds are added. Visit althea.net/top-up"