name: Build dependencies

on:
  push:
    branches:
      - jrd/*
  pull_request:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy.yml
