name: Build dependencies

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: debian
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run playbook
        run: |
          ls
          echo $PATH
