name: Firmware Dependency Check

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ansible syntax check
        run: |
          pip3 install --user ansible
          ansible-playbook -i hosts --syntax-check --list-tasks *.yml
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: docker:latest
          shell: bash
          run: |
            echo "first line"
            echo "second line"
