name: Firmware Dependency Check

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: fedora:latest
          shell: /bin/bash
          run: |
            pip3 install --user ansible
            ansible-galaxy collection install -r requirements.yml
